import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/1.LessonPlanning-Lisa.png',
    title: 'Lesson Planning',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/courses/2.Quiz-Qasim.png',
    title: 'Quiz',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/courses/3.AutomatedEssayScoringandFeedback-Elsa.png',
    title: 'Automated Essay Scoring and Feedback',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/courses/5.MathsQuiz-Matthew.png',
    title: 'Maths Quiz',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/courses/6.MathLessonPlanner-Lucy.png',
    title: 'Math Lesson Planner',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/courses/7.Videotonotes-Vincent.png',
    title: 'Video to notes',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/courses/8.VideotoQuizBot.png',
    title: 'Video to Quiz Bot',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 8,
    cover: '/images/courses/9.DetectAI-Writing&Plagiarism-Ali.png',
    title: 'Detect AI-Writing & Plagiarism',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 9,
    cover: '/images/courses/10.PowerPointPresentationPriyanka.png',
    title: 'PowerPoint Presentation',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermediate',
  },
  {
    id: 10,
    cover: '/images/courses/11ReportsGeneraor-Bob.png',
    title: 'Reports Generator',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
  },
  {
    id: 11,
    cover: '/images/courses/12ESLActivitySuggestionAmira.png',
    title: 'ESL Activity Suggestion',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Intermediate',
  },
  {
    id: 12,
    cover: '/images/courses/13Document&WbLinkQuizOmari.png',
    title: 'Document & Web Link Quiz',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Intermediate',
  },
  {
    id: 13,
    cover: '/images/courses/14HomeworkAssignmentCreatorIshan.png',
    title: 'Homework Assignment Creator',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Beginner',
  },
  {
    id: 14,
    cover: '/images/courses/15TestCreator-Jack.png',
    title: 'Test Creator',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 15,
    cover: '/images/courses/16ClassroomIcebreakerIdeas-Anne.png',
    title: 'Classroom Icebreaker Ideas',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
  }
]
